# Generated by Django 4.2.4 on 2023-09-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_alter_event_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.CharField(
                choices=[("C", "Cultural"), ("SE", "Seminar"), ("S", "Sports")],
                max_length=2,
                verbose_name="Category",
            ),
        ),
    ]
